import REM2D_main as r2d

if __name__=="__main__":
	# A config file and a directory are needed to do an evolutionary run. By default, the working directory is used. You can store and adjust a config file in here. 
	# if no config file is present, one will automatically be generated by ConfigurationMaker.py
	#	config, dir = r2d.setup(directory = "D:/folder/")	
	# without the directory argument, the program will run in default working directory
	config, dir = r2d.setup()	
	experiment = r2d.run2D(config,dir)
	experiment.run(config)


